steps:
  - name: gcr.io/kaniko-project/executor:latest
    id: build-cronclient
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/registry/cronclient:latest
      - --dockerfile=cronclient/Dockerfile

  - name: gcr.io/kaniko-project/executor:latest
    id: build-customer
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/registry/customer:latest
      - --dockerfile=customer/Dockerfile

  - name: gcr.io/kaniko-project/executor:latest
    id: build-profile-v1
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/registry/profile:v1
      - --dockerfile=profile/v1/Dockerfile

  - name: gcr.io/kaniko-project/executor:latest
    id: build-profile-v2
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/registry/profile:v2
      - --dockerfile=profile/v2/Dockerfile

  - name: gcr.io/kaniko-project/executor:latest
    id: build-order
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/registry/order:latest
      - --dockerfile=order/Dockerfile
