// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: add.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddSerivceClient is the client API for AddSerivce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddSerivceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type addSerivceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddSerivceClient(cc grpc.ClientConnInterface) AddSerivceClient {
	return &addSerivceClient{cc}
}

func (c *addSerivceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/proto.AddSerivce/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddSerivceServer is the server API for AddSerivce service.
// All implementations must embed UnimplementedAddSerivceServer
// for forward compatibility
type AddSerivceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	mustEmbedUnimplementedAddSerivceServer()
}

// UnimplementedAddSerivceServer must be embedded to have forward compatible implementations.
type UnimplementedAddSerivceServer struct {
}

func (UnimplementedAddSerivceServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAddSerivceServer) mustEmbedUnimplementedAddSerivceServer() {}

// UnsafeAddSerivceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddSerivceServer will
// result in compilation errors.
type UnsafeAddSerivceServer interface {
	mustEmbedUnimplementedAddSerivceServer()
}

func RegisterAddSerivceServer(s grpc.ServiceRegistrar, srv AddSerivceServer) {
	s.RegisterService(&AddSerivce_ServiceDesc, srv)
}

func _AddSerivce_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddSerivceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddSerivce/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddSerivceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddSerivce_ServiceDesc is the grpc.ServiceDesc for AddSerivce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddSerivce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddSerivce",
	HandlerType: (*AddSerivceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AddSerivce_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "add.proto",
}
