---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: access-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: access
              image: asia-northeast1-docker.pkg.dev/cuddly-train/registry/access:latest
