---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronclient
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronclient
              image: asia-northeast1-docker.pkg.dev/cuddly-train/registry/cronclient:latest
              imagePullPolicy: Always
              args:
                - customer-service:80
                - "5"
                - "10"
              resources:
                requests:
                  cpu: 250m
                  memory: 512Mi
          nodeSelector:
            cloud.google.com/gke-spot: "true"
          restartPolicy: Never
