---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deploy
  labels:
    app: customer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-deploy
  template:
    metadata:
      labels:
        app: customer-deploy
    spec:
      containers:
        - name: web
          env:
            - name: PORT
              value: "80"
            - name: PROFILE_ADDRESS
              value: profile-service:80
            - name: ORDER_ADDRESS
              value: order-service:80
          image: asia-northeast1-docker.pkg.dev/cuddly-train/registry/customer:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      nodeSelector:
        cloud.google.com/gke-spot: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-deploy
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: customer-service
                port:
                  number: 80
