---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
  labels:
    app: order-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-deploy
  template:
    metadata:
      labels:
        app: order-deploy
    spec:
      containers:
        - name: web
          env:
            - name: PORT
              value: "80"
          image: asia-northeast1-docker.pkg.dev/cuddly-train/registry/order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      nodeSelector:
        cloud.google.com/gke-spot: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-deploy
  ports:
    - port: 80
      protocol: TCP
