---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deploy
  labels:
    app: profile-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-deploy
  template:
    metadata:
      labels:
        app: profile-deploy
    spec:
      containers:
        - name: web
          env:
            - name: PORT
              value: "80"
          image: asia-northeast1-docker.pkg.dev/cuddly-train/registry/profile:v1
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      nodeSelector:
        cloud.google.com/gke-spot: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-deploy
  ports:
    - port: 80
      protocol: TCP
